### ISSUE TITLE
Sample library it's full of nazi symbol......

### ISSUE THREAD

**Issue by giorgionetg** [mrdoob/glsl-sandbox#55] opened 2019-01-16 12:24 UTC
Thanks for cleaning this awkward stuff... 👍 

it's just an example. And it's just full of these!

http://glslsandbox.com/e#51458.0

**Comment by DagAgren** [comment] 2019-01-21 14:32
The issue for doing any kind of moderation was closed: 
https://github.com/mrdoob/glsl-sandbox/issues/36

**Comment by mrdoob** [comment] 2019-01-28 13:18
Duplicate of #36 indeed.

**Closed by mrdoob** 2019-01-28 13:18 UTC
