### ISSUE TITLE
does not work on ios (

### ISSUE THREAD

**Issue by makc** [mrdoob/glsl-sandbox#33] opened 2015-03-05 12:06 UTC
wanted to test one thing quickly but no

**Comment by rustinlee** [comment] 2015-04-08 21:36
Which iOS? Which device?

**Comment by makc** [comment] 2015-04-08 22:48
ipad3 with ios8

**Comment by mrdoob** [comment] 2015-04-10 18:14
Any errors?

**Comment by makc** [comment] 2015-04-10 18:16
I did not have it connected to mac at the time, so I would not know.

**Comment by makc** [comment] 2015-04-10 18:18
By "does not work" I mean it would show me black screen after clicking the thumbnail.

**Comment by ncacace** [comment] 2017-08-27 09:57
Works on iOS iPads but not on mobile
Other WebGL examples from other sites work so it's not WebGL

It displays a black screen.

It probably has something to do with how each example filter is loaded within the same screen (I don't have it connected in debug at the moment)

**Comment by ncacace** [comment] 2017-08-27 10:12
Each example's resolution progressively degrades on iPad within minutes. Most probably due to an accumulated error with decimal approximation. 

I haven't experienced this with the desktop system

I'm not sure if this is caused by WebGL or just with the glsl-sandbox implimentation

**Comment by mrdoob** [comment] 2017-12-30 04:31
Works fine here... 🤔

![c805a837-f96a-4343-a1f6-9bb32e895910](https://user-images.githubusercontent.com/97088/34451323-4ad3d8c4-ecd7-11e7-957f-85d7c3ab4519.png)

**Comment by ncacace** [comment] 2017-12-30 11:54
I'm sorry but this was a while ago and there is no reference of the example that wasn't working...

There is no reference to the example that you are generating the screen shot with. Could you include a link to the actual page so that I can check it on my iPad (...also I'm not even sure that what you are looking at was what I was looking at when I posted my message - so it may not even be Apples and apples) I've updated my second post with a link and a screenshots but I can't remember which wasn't working - sorry)

**Comment by mrdoob** [comment] 2017-12-31 00:59
I've updated my post with a link.

**Comment by mrdoob** [comment] 2017-12-31 01:02
Oh, I see your screenshots now. These are probably precision issues with the iPad's GPU. Unfortunately there is nothing we can do about it.

**Comment by mrdoob** [comment] 2017-12-31 01:02
Closing this.

**Closed by mrdoob** 2017-12-31 01:02 UTC
